/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configInicio;

import Notificaciones.DesktopNotify;
import alertas.WarningAlert;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import necesario.FadeEffect;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Luis mora
 */
public class Configuracion extends javax.swing.JFrame {

    private boolean minimiza = false;
    private int clic = 0;

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        this.setLocationRelativeTo(this);

        FadeEffect.fadeInFrameSplash(this, 10, 0.1f);

        this.txtNombre.requestFocus();
        this.lblInfo.setText("");
        this.btnAtras.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMinimizar = new rojerusan.RSButtonMetro();
        btnCerrar = new rojerusan.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnlUsuario = new javax.swing.JPanel();
        txtUser = new rojerusan.RSMetroTextFullPlaceHolder();
        txtPass = new rojerusan.RSMetroTextPassPlaceHolderView();
        lblInfo = new javax.swing.JLabel();
        txtNombre = new rojerusan.RSMetroTextFullPlaceHolder();
        pnlVerificar = new javax.swing.JPanel();
        lblInfo4 = new javax.swing.JLabel();
        lblInfo5 = new javax.swing.JLabel();
        lblInfo6 = new javax.swing.JLabel();
        lblUs = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblInfo9 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        pnlCargando = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblInfo7 = new javax.swing.JLabel();
        lblInfo8 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        btnAceptar = new rojerusan.RSButtonHover();
        btnAtras = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192), 5));

        btnMinimizar.setBackground(new java.awt.Color(255, 0, 51));
        btnMinimizar.setText("__");
        btnMinimizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnMinimizar.setGrosorLinea(3);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(255, 0, 51));
        btnCerrar.setText("X");
        btnCerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCerrar.setGrosorLinea(3);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-login.png"))); // NOI18N

        lblInfo2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(0, 207, 211));
        lblInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo2.setText("RS");

        lblInfo1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblInfo1.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo1.setText("CONFIGURAR USUARIO SUPER ADMIN");

        pnlUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuario.setName("pnlUsuario"); // NOI18N

        txtUser.setPlaceholder("NOMBRE DE USUARIO");
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });

        txtPass.setPlaceholder("CONTRASEÑA");
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(200, 0, 0));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("INGRESAR USUARIO Y CONTRASEÑA");

        txtNombre.setMayusculas(true);
        txtNombre.setPlaceholder("NOMBRE COMPLETO");
        txtNombre.setSoloLetras(true);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(170, 170, 170))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        rSPanelsSlider1.add(pnlUsuario, "card2");

        pnlVerificar.setBackground(new java.awt.Color(255, 255, 255));
        pnlVerificar.setName("pnlVerificar"); // NOI18N

        lblInfo4.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblInfo4.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo4.setText("NOMBRE DE USUARIO:");

        lblInfo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblInfo5.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo5.setText("VERIFIQUE QUE SUS DATOS SEAN CORRECTOS");

        lblInfo6.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblInfo6.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo6.setText("CONTRASEÑA:");

        lblUs.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblUs.setForeground(new java.awt.Color(0, 207, 211));
        lblUs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUs.setText("USUARIO");

        lblPass.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblPass.setForeground(new java.awt.Color(0, 207, 211));
        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPass.setText("PASSWORD");

        lblInfo9.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblInfo9.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo9.setText("NOMBRE COMPLETO:");

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 207, 211));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("NOMBRE");

        javax.swing.GroupLayout pnlVerificarLayout = new javax.swing.GroupLayout(pnlVerificar);
        pnlVerificar.setLayout(pnlVerificarLayout);
        pnlVerificarLayout.setHorizontalGroup(
            pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo5, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerificarLayout.createSequentialGroup()
                        .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInfo6)
                            .addComponent(lblInfo9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlVerificarLayout.setVerticalGroup(
            pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo5)
                .addGap(60, 60, 60)
                .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo9)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo4)
                    .addComponent(lblUs))
                .addGap(14, 14, 14)
                .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo6)
                    .addComponent(lblPass))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pnlVerificar, "card3");

        pnlCargando.setBackground(new java.awt.Color(255, 255, 255));
        pnlCargando.setName("pnlCargando"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultas/cargando.gif"))); // NOI18N

        lblInfo7.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblInfo7.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo7.setText("CONFIGURANDO USUARIO SUPER ADMIN");

        lblInfo8.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblInfo8.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo8.setText("ESPERE UN MOMENTO...");

        javax.swing.GroupLayout pnlCargandoLayout = new javax.swing.GroupLayout(pnlCargando);
        pnlCargando.setLayout(pnlCargandoLayout);
        pnlCargandoLayout.setHorizontalGroup(
            pnlCargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargandoLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(255, 255, 255))
            .addGroup(pnlCargandoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCargandoLayout.setVerticalGroup(
            pnlCargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargandoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblInfo7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo8)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(pnlCargando, "card4");

        lblInfo3.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        lblInfo3.setForeground(new java.awt.Color(0, 112, 192));
        lblInfo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo3.setText("Clinyc");

        btnAceptar.setText("SIGUIENTE");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblInfo1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(lblInfo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblInfo1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblInfo2)
                                    .addComponent(lblInfo3))
                                .addGap(18, 18, 18)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        if (!minimiza) {
            minimiza = false;
        } else {
            minimiza = true;
        }
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        WarningAlert a = new WarningAlert(this, false);
        WarningAlert.msj1.setText("¿Deseas salir del sistema?");
        WarningAlert.msj2.setVisible(false);
        WarningAlert.msj3.setVisible(false);
        WarningAlert.lblTipo.setText("Salir");
        WarningAlert.lblTipo.setVisible(false);
        WarningAlert.lblId.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        this.lblInfo.setText("");
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        this.lblInfo.setText("");
    }//GEN-LAST:event_txtPassKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (this.txtUser.getText().isEmpty() || String.valueOf(this.txtPass.getPassword()).isEmpty()
                || this.txtNombre.getText().isEmpty()) {

            this.lblInfo.setText("¡Todos los campos son requeridos!");
            this.txtNombre.requestFocus();
        } else {
            boolean camposCorrectos = true;

            if (String.valueOf(this.txtPass.getPassword()).length() < 8) {
                this.lblInfo.setText("¡Debés ingresar 8 caracteres como mínimo!");
                camposCorrectos = false;
                this.txtPass.requestFocus();
            }

            if (clic == 1) {
                rSPanelsSlider1.slidPanel(5, pnlCargando, RSPanelsSlider.direct.Right);
                this.btnAtras.setVisible(false);
                this.btnAceptar.setVisible(false);

                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            Thread.sleep(8000);
                            registraUser();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }).start();
            }

            if (camposCorrectos && clic == 0) {
                rSPanelsSlider1.slidPanel(5, pnlVerificar, RSPanelsSlider.direct.Right);
                this.btnAtras.setVisible(true);
                this.btnAceptar.setText("ACEPTAR");
                this.lblUs.setText(this.txtUser.getText());
                this.lblPass.setText(String.valueOf(this.txtPass.getPassword()));
                this.lblNombre.setText(this.txtNombre.getText());
                clic++;
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        rSPanelsSlider1.slidPanel(5, pnlUsuario, RSPanelsSlider.direct.Left);
        this.btnAceptar.setText("SIGUIENTE");
        clic--;
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnAceptar;
    private rojerusan.RSButtonHover btnAtras;
    private rojerusan.RSButtonMetro btnCerrar;
    private rojerusan.RSButtonMetro btnMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblInfo4;
    private javax.swing.JLabel lblInfo5;
    private javax.swing.JLabel lblInfo6;
    private javax.swing.JLabel lblInfo7;
    private javax.swing.JLabel lblInfo8;
    private javax.swing.JLabel lblInfo9;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUs;
    private javax.swing.JPanel pnlCargando;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JPanel pnlVerificar;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSMetroTextFullPlaceHolder txtNombre;
    private rojerusan.RSMetroTextPassPlaceHolderView txtPass;
    private rojerusan.RSMetroTextFullPlaceHolder txtUser;
    // End of variables declaration//GEN-END:variables

    private void registraUser() {
        usuarios.Sentencias s = new usuarios.Sentencias();

        //s.setId(1);
        s.setNombre(this.txtNombre.getText());
        s.setUsuario(this.txtUser.getText());
        s.setPassword(String.valueOf(this.txtPass.getPassword()));
        s.setTipo_usuario("SUPER ADMIN");

        if (usuarios.Opciones.registrar(s)) {           
            new splash.SplashScreen().setVisible(true);
            DesktopNotify.showDesktopMessage("CONFIGURAR USUARIO SUPER ADMIN...", "El usuario SUPER ADMIN fue configurado con exito. Ahora ya "
                    + "puedes iniciar sesión en el sistema.", DesktopNotify.INFORMATION, 8000);
            this.dispose();
        }
    }
}
